L10N.en =
{
	"lang-switch": "EN",
    "promo-banner-text": "&#9679;&#9679;&#9679; MENU &#9679;&#9679;&#9679;<br />open 12:00 - 20:00",
    "header-desc-text": "&#9656; Hot BBQ and Russian cuisine",
    "header-title-text": "SOON BEAR",
    "cartPreview": "<div class='cart-preview-title'>Cart is empty.</div>",

    "cart-preview-title": "Cart",
    "cart-preview-total-text": "TOTAL:&nbsp",
    "cart-modal-title": "Cart",
    "cart-not-working-hours-text": "NON working hours. Your order will be processed as soon as delivery opens. I have find our working hours at the top of the main page.",
    "cart-title": "Cart",
    "cart-total-text": "TOTAL:&nbsp",
    "form-tg-name": "Telegram nick *",
    "form-phone": "Vietnam mobile (for delivery boy) *",
    "form-payment-type": "Payment type *",
    "form-payment-type-cash": "Cash on delivery",
    "form-payment-type-qr": "QR code (Vietnamese bank)",
    "form-address": "Delivery address *",
    "form-comment": "Comment",
    "form-submit": "Confirm order",
    "inp-name": "@user",
    "inp-phone": "+84 or Not to inform admin contact other way",
    "inp-address": "Use geolocation or enter the exact address",
    "inp-comment": "Special requirements or promo code",
    "hist-open-btn": "📋 History (<span id='historyCount'>0</span>)",
    "hist-modal-title": "Orders history",
    "hist-repeat-btn": "Reorder",
    "hist-empty": "History is empty",

    "alert-location-not-supported": "Your browser doesn't support geolocation",
    "alert-location-not-found": "Can't find your location. Please enter address manually.",
    "alert-fill-required-fields": "Please fill all required fields.",
    "alert-empty-cart": "Cart is empty.",
    "alert-order-completed": "Order have been confirmed. Admin will contact you soon.",
    "alert-order-not-found": "Order not found",

    "non-working-hours-alert": "&#10069;&#10069;&#10069; Our work hours is 12:00 - 20:00 &#10069;&#10069;&#10069;<br>Please check time before placing the order",
}
;
